### ISSUE TITLE
There is no license associated with this repo, nor is there a license file

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-Erigon#49]
This repo is not assigned a license nor does it have a license file in it as it needs to to comply with the upstream license which is not GPL-3.0 its LGPL-3.0 and the only mention we have of a license is a typo in the manifest from the SDK.

**Comment by tropicar** [comment]
I have added the license file GPL3.0 if you think is ok close the issue

**Comment by alexpeterson91** [comment]
https://github.com/ledgerwatch/erigon/blob/devel/COPYING
Things get complicated here with whether or not this is considered a library which is what Ledgerwatch licensed it as under LGPL-3.0. the info on the linked license page makes it seem that we need to use the same license, however it has a carveout for similar licenses, of which the GPL-3.0 is as a way to release it.  

However closer inspection of the upstream repo has more files we need to include another license file and a copyright file all must be included including these 2 below

- [AUTHORS](https://github.com/ledgerwatch/erigon/blob/devel/AUTHORS)
- https://github.com/ledgerwatch/erigon/blob/devel/COPYING.LESSER

**Comment by alexpeterson91** [comment]
Ok after some further review i think we are good with your fix as is
