### ISSUE TITLE
Add prunning option

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-Erigon#76]
The size of Erigon package is around 2Tb, it would be good to add the running option to reduce the size. And it would be a good idea to add this option in the wizard to make it easier to enable.

**Comment by mdvries** [comment]
This is a great idea. I did try by just adding --prune=htcr to the EXTRA_OPT section but then got the following error in the log and the package keeps restarting:

err="not allowed change of --prune flag, last time you used: "

As if erigon starts with an empty --prune flag and the --prune=htcr conflict with that.

**Comment by tropicar** [comment]
The entrypoint.sh execute the binary without the extraopts option once time, we are fixing it, in the next release will be fixed.
